<?xml version="1.0"?>
<package format="3">
  <name>pid_controll</name>
  <version>0.0.0</version>
  <description>PID controller package</description>
  <maintainer email="Mugis@todo.todo">Mugis</maintainer>
  <license>TODO</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>